site_name: The Data Armory
site_description: Insightful Python Fundamentals for Beginners

repo_url: https://github.com/everndah/python_tutorials
repo_name: everndah/python_tutorials

theme:
  name: material

  # Pallet Color
  palette:
    primary: black

  # Site Font
  font:
    text: Roboto

  features:
    - navigation.footer
    - content.code.copy
    - content.code.py.annotate
    - search.suggest
    - search.highlight
    - toc.follow
    - navigation.instant
    - navigation.top

extra:
  # Social Links
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@thedataarmory
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TheDataArmory

  markdown_extensions:
    - pymdownx.highlight:
      anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - pymdownx.arithmatex:
      generic: true
    - footnotes
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.mark
    - attr_list
    - pymdownx.emoji:
      #emoji_index: !!python/name:materialx.emoji.twemoji
      #emoji_generator: !!python/name:materialx.emoji.to_svg
  
plugins:
  - mkdocs-jupyter:
      ignore_h1_titles: True
nav:
    - Home: "index.md"
    - 00. What is Python: 00_what_is_python.ipynb
    - 01. Python Variables: 01_variables_in_python.ipynb
    - 02. Data Types: 02_python_data_types.ipynb
    - 03. Python Comments:  03_python_comments.ipynb
    - 04. Python Strings: 04_python_strings.ipynb
  
#Footer Copyright Info
copyright: Copyright &copy; 2023 The Data Armory
